### ISSUE TITLE
No JAR in maven central release

### ISSUE THREAD

**Issue by Sytten** [FasterXML/jackson-datatypes-collections#13]
Hi,
I want to use the lib, but there are no JAR in the maven central releases...
Is it possible to add them in the future releases.
Thanks

**Comment by cowtowncoder** [comment]
Which jar? All jars should be available from Maven Central normally. Please specify which one you are trying to refer to (Maven coordinates).

**Comment by Sytten** [comment]
https://search.maven.org/#artifactdetails%7Ccom.fasterxml.jackson.datatype%7Cjackson-datatypes-collections%7C2.8.8%7Cpom

**Comment by Sytten** [comment]
I ended up using directly the guava datatype and it worked.

**Comment by cowtowncoder** [comment]
Ah. The parent component is of type `pom` (and not `jar` or `bundle`), which is why your reference would fail.

Your usage is correct: individual collection modules need to be referenced separately; parent pom is not of much use as it only specifies settings for individual components, and no code.

**Comment by Petikoch** [comment]
@cowtowncoder I run into the same problem... 

Because https://github.com/FasterXML/jackson-datatype-guava is "deprecated", I tried to use jackson-datatypes-collections as dependency instead... but there is no jar in maven central... etc

Is the real issue maybe the deprecation of jackson-datatype-guava? Maybe this shouldn't be deprecated?

Have a nice day and best regards,
Peti

**Comment by cowtowncoder** [comment]
@Petikoch Only repository is deprecated not the jar. It is bit confusing, but please still use the artifact `jackson-datatype-guava`. Parent pom should not be directly used.
I hope this makes mopre sense.

**Comment by rhengeveld** [comment]
Might I suggest to add this information to the project page? 🙂 

It took me a while to figure out to add the (Guava) module - rather than the parent - as dependency
```
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-guava</artifactId>
</dependency>
```
and to correctly register the `GuavaModule` (Spring Boot 2) to get the (de)serializers found
```
@Bean
public Jackson2ObjectMapperBuilderCustomizer customize()
{
    return builder -> builder.modules( new GuavaModule() );
}
```

Now that's done - this is awesome work! Much appreciated.

**Comment by cowtowncoder** [comment]
@rhengeveld Good idea, added!
