### ISSUE TITLE
SetMultimap should be deserialized to a LinkedHashMultimap by default

### ISSUE THREAD

**Issue by twbecker** [FasterXML/jackson-datatypes-collections#25]
Currently, when deserializing to a field declared simply as a `SetMultimap`, a `HashMultimap` is used as the implementation. This is at odds with Jackson's default behavior for normal `Map`s where a `LinkedHashMap` is used to preserve the ordering present in the JSON. It seems like the Guava module should analogously use `LinkedHashMultimap` as the default `SetMultimap` implementation.

**Comment by cowtowncoder** [comment]
Sounds reasonable to me; somehow did not notice this so apologies for ultra-slow follow up.
Seems like a simple change if anyone wants to have a look: should go in 2.12 branch to be included in 2.12.0 since it is behavior change (small but visible, likely to cause some false test fails somewhere, wrt fragile tests & ordering assumptions).

**Comment by Migwel** [comment]
I'd like to work on this, if it hasn't been picked up yet

**Comment by cowtowncoder** [comment]
@Migwel yes, go for it! :)
