### ISSUE TITLE
Range property name (de)serialisation doesn't respect property naming strategy

### ISSUE THREAD

**Issue by philleonard** [FasterXML/jackson-datatypes-collections#56]
Field names in the Guava `Range<T>` are serialised and deserialised with the hard coded values `lowerEndpoint`,  `lowerBoundType`, `upperEndpoint` and `upperBoundType`:
```json
    {
      "lowerEndpoint": 1,
      "lowerBoundType": "OPEN",
      "upperEndpoint": 10,
      "upperBoundType": "CLOSED"
    }
```
For consistent JSON field naming it would be nice to support other property naming strategies. For example snake case:

```json
    {
      "lower_endpoint": 1,
      "lower_bound_type": "OPEN",
      "upper_endpoint": 10,
      "upper_bound_type": "CLOSED"
    }
```
Please see here for the basic idea https://github.com/philleonard/jackson-datatypes-collections/commit/8a3f36fbb02d1ca33f22d5afc4754a321af166aa. Happy to open this as a PR and change to whatever is the correct way of formatting field names when writing them as strings.

**Comment by cowtowncoder** [comment]
True, since there's custom (de)serializer, instead of default POJO one, field names are essentially hard-coded. Would be happy to work on improvement.

On proof-of-concept, calling field name mutators on-the-fly is bit cost-prohibitive, so I would not want that to occur at time of (de)serialization. But you should be able to do that instead in `createContextual()` (implement `ContextualSerializer` / `ContextualDeserializer`), and then re-create new (de)serializer if naming convention exists. That is the canonical way of applying such changes anyway. 

Actually, come to think of this, there may be even simpler way to achieve early changing. (De)Serializers are registered by `GuavaModule`, via `GuavaDeserializers` and `GuavaSerializers`.
Methods (findXxXDeserializer() / findSerializer()) are passed `BeanDescription` (as well as `config`), and that should have access to naming convention configuration as well.

Let me know if you need more information on above: I don't think I have done this for other custom/external (de)serializers but there should be no blockers.

**Comment by philleonard** [comment]
Hi @cowtowncoder, thanks for your quick response. `BeanDescription` (cast to a `BasicBeanDescription`) only has the `protected` field access to the `MapperConfig` where we can gain reference to the `PropertyNamingStrategy`. So I don't see any way to do this without reflection or a change to `jackson-databind` unless I am missing something?

I have gone ahead with your first suggestion for the time being https://github.com/FasterXML/jackson-datatypes-collections/pull/57. Let me know what you think.
