### ISSUE TITLE
Support for Guava 29?

### ISSUE THREAD

**Issue by markwoon** [FasterXML/jackson-datatypes-collections#68]
`jackson-datatype-guava`  cannot be used with Guava >= 28.0.0 in OSGI.

Is there a reason for this restriction?  If not, can we please lift it?

I'll submit a PR if that'll help...

**Comment by cowtowncoder** [comment]
I do not recall a reason for this limitation, maybe worth asking about on `jackson-dev` list?
If you could run test suite with 29.x to validate, that could help.

**Comment by markwoon** [comment]
All tests pass both `29.0-jre` and `29.0-android`.

I've also posted the query to jackson-dev.

**Comment by markwoon** [comment]
@cowtowncoder You've left comments in `pom.xml` wondering why this limitation exists as well.

Wouldn't it make more sense to just have a lower bound so you don't have to keep changing this?  At least until there's a reason to put an upper bound to the version range?

**Comment by cowtowncoder** [comment]
I think this limitation came from a contribution related to OSGi metadata inclusion, to allow ranges instead of specific version; that is, to relax limitations. I can see why there is minimum version, but it seems questionable to specify maximum since there simply is no information to base it on.

So, how about this: we can initially just update limit for 2.11.x (or even 2.10.x, if there will be new patches), and remove max from 2.12. Just in case there was some benefit to upper bound?

**Comment by markwoon** [comment]
Works for me.  I've just rolled my own for now, although I'd love an official version.

**Comment by cowtowncoder** [comment]
I'll add my suggestion on mailing list; basically "raise max to 29 for 2.11; remove limit (use... 99? assuming OSGi requires some limit to use ranges) for later"

**Comment by markwoon** [comment]
Yeah, OSGI requires an upper bound if you use ranges.

**Comment by cowtowncoder** [comment]
Ok. I don't think use of something like 99 should be problematic but wanted to know what best practices might suggest. I added this to my TODO list (https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress), will just wait for a bit for feedback. But will make it in 2.11.2 / 2.12.0 (and if there will ever be 2.10.6, think I'll backport it in 2.10 branch for fun).

**Comment by cowtowncoder** [comment]
I'll go ahead and proceed with the suggestion...
